name: Account
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  cwd: ${{github.workspace}}/packages/account

defaults:
  run:
    working-directory: ${{github.workspace}}/packages/account

jobs:
  test-account:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 13, 14]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - run: npm run bootstrap
        working-directory: ${{github.workspace}}
      
      - run: npm run build
        working-directory: ${{github.workspace}}

      - run: npm run lint
      - run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: account
        if: ${{ matrix.node-version == 12 }}
