name: VM Nightly
on:
  schedule:
    - cron: 0 0 * * *

env:
  cwd: ${{github.workspace}}/packages/vm

defaults:
  run:
    working-directory: ${{github.workspace}}/packages/vm

jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1

      - run: npm run bootstrap
        working-directory: ${{github.workspace}}
        
      - run: npm run build
        working-directory: ${{github.workspace}}

      - run: npm run test:API
      - run: npm run test:API:browser

  test-vm-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1

      - run: npm run bootstrap
        working-directory: ${{github.workspace}}

      - run: npm run build
        working-directory: ${{github.workspace}}

      - run: npm run test:state:allForks

  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1

      - run: npm run bootstrap
        working-directory: ${{github.workspace}}

      - run: npm run build
        working-directory: ${{github.workspace}}

      - run: npm run test:blockchain
        working-directory: '${{ env.cwd }}'

  test-vm-slow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      
      - run: npm run bootstrap
        working-directory: ${{github.workspace}}

      - run: npm run build
        working-directory: ${{github.workspace}}
      
      - run: run test:state:slow
